chore: merge changes from `main` (#2064)
* fix: don't refetch rebac relations if there is an error to prevent an infinite loop (#2038)

* chore(ci): improve e2e performance (#2039)

* chore(ci): block external requests in e2e tests (#2046)

* fix: missed quote in release workflow (#2041)

* fix: missed quote in release workflow

* fix: invalid usage of `secrets` in action

* chore: move disableControllerUUIDMasking into model-poller (#2048)

* chore: move afterControllerListFetched to OIDCAuth

* chore: remove unnecessary log

* chore: move disableControllerUUIDMasking into model-poller

* chore: Update docs for restarting local JIMM setup (#2049)

* feat: Implement client for model migration (#2035)

* feat: Implement client for model migration

* feat: Add client for listMigrationTargets

* chore: clean up JIMM client code

* fix: remove dns-name and fix setting the port (#2052)

* feat: cross-platform build and publish docker image to ghcr

* refactor: Consolidate redundant code on models list page (#2057)

* chore: Consolidate redundant code on models list page

* fix: Fix breaking tests

* fix: Fix breaking E2E tests

* refactor: introduce utility for conditional tabel cell rendering

* test: update run playwright action and keycloak backend e2e test fix (#2059)

* ci: set correct working directory  for run-playwright action

* ci: remove setup-node cache

Using cache-dependency-path comes with the caveat that no relative paths are allowed other you get the following error,

"Error: Invalid pattern '<path>'. Relative pathing '.' and '..' is not allowed.

* ci: specify node-version

* test: remove CLI login for keycloak user creation

* ci: use a normalised path

Tests successfully passed but the upload-artifact step failed because it doesn't accept a relative path so normalise first and use that value.

* ci: remove node-version input

* ci: allow workflow to specify dashboard address scheme

When running the dashboards tests from the jimm repo, the dashboard is served via https, so allow the workflow to specify the scheme rather than hardcoding it in the action.

* ci: add scheme for automatically determined dashboard URL

* ci: use a fixed version of jimm in CI tests

Using a fixed version of JIMM in CI means that you are not guessing what broke when you made a change, jimm or the dashboard.
Then when a new feature is released in jimm that the dashboard wants to take advantage of the new feature.

* feat: env var configuration of dashboard image (#2058)

* Build(deps): Bump form-data from 4.0.0 to 4.0.4

---
updated-dependencies:
- dependency-name: form-data
  dependency-version: 4.0.4
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>

* feat: add haproxy-route interface for the machine charm

* chore(docs): add TLS recommendations (#2060)

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: huwshimi <huwshimi@users.noreply.github.com>
Co-authored-by: Urvashi Sharma <55801560+Ninfa-Jeon@users.noreply.github.com>
Co-authored-by: Kian Parvin <46668016+kian99@users.noreply.github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

diff --git a/.github/actions/setup-jimm/action.yml b/.github/actions/setup-jimm/action.yml
--- a/.github/actions/setup-jimm/action.yml
+++ b/.github/actions/setup-jimm/action.yml
@@ -61,12 +61,12 @@ runs:
     - name: Wait for IAM
       uses: nick-fields/retry@v3
       with:
-        timeout_minutes: 10
-        max_attempts: 2 # Retry the wait-for in case it gets stuck and times out. If it fails on the second try it's probably a real error.
+        timeout_minutes: 1
+        max_attempts: 5 # Retry the wait-for with a short timeout in case it gets stuck and times out. If it fails after multiple tries it's probably a real error.
         command: |
           # Wait for everything to be ready except kratos-external-idp-integrator
           # which will remain as blocked as we're not using an external identity provider.
-          juju wait-for model iam --query='forEach(applications, app => (app.name == "kratos-external-idp-integrator" && app.status=="blocked") || (app.name != "kratos-external-idp-integrator" && app.status=="active"))'
+          juju wait-for model iam --timeout=1m --query='forEach(applications, app => (app.name == "kratos-external-idp-integrator" && app.status=="blocked") || (app.name != "kratos-external-idp-integrator" && app.status=="active"))'
     - name: Create IAM offers for cross-model relations
       shell: bash
       run: |
@@ -78,9 +78,9 @@ runs:
     - name: Wait for Kratos
       uses: nick-fields/retry@v3
       with:
-        timeout_minutes: 10
-        max_attempts: 2 # Retry the wait-for in case it gets stuck and times out. If it fails on the second try it's probably a real error.
-        command: juju wait-for unit kratos/0
+        timeout_minutes: 1
+        max_attempts: 5 # Retry the wait-for with a short timeout in case it gets stuck and times out. If it fails after multiple tries it's probably a real error.
+        command: juju wait-for unit kratos/0 --timeout=1m
     - name: Create admin user
       shell: bash
       run: |
@@ -101,9 +101,9 @@ runs:
     - name: Wait for Postgres
       uses: nick-fields/retry@v3
       with:
-        timeout_minutes: 10
-        max_attempts: 2 # Retry the wait-for in case it gets stuck and times out. If it fails on the second try it's probably a real error.
-        command: juju wait-for unit postgresql/0 # Wait for postgres to prevent issues when relating to openfga: https://github.com/canonical/openfga-operator/issues/25.
+        timeout_minutes: 1
+        max_attempts: 5 # Retry the wait-for with a short timeout in case it gets stuck and times out. If it fails after multiple tries it's probably a real error.
+        command: juju wait-for unit postgresql/0 --timeout=1m # Wait for postgres to prevent issues when relating to openfga: https://github.com/canonical/openfga-operator/issues/25.
     - name: Add JIMM relations
       shell: bash
       run: |
@@ -115,15 +115,15 @@ runs:
     - name: Wait for openfga
       uses: nick-fields/retry@v3
       with:
-        timeout_minutes: 10
-        max_attempts: 3
+        timeout_minutes: 1
+        max_attempts: 5 # Retry the wait-for with a short timeout in case it gets stuck and times out. If it fails after multiple tries it's probably a real error.
         command: |
           STATUS=$(juju status --format json | yq .applications.openfga.application-status.current)
           if [ "$STATUS" == "error" ]; then
             # Sometimes the openfga unit will get into an error state, so resolve and try again.
             juju resolved openfga/0
           fi
-          juju wait-for unit openfga/0
+          juju wait-for unit openfga/0 --timeout=1m
     - name: Add JIMM relations and certs
       shell: bash
       run: |
@@ -131,6 +131,12 @@ runs:
         juju relate jimm admin/iam.self-signed-certificates
         juju deploy self-signed-certificates jimm-cert
         juju relate ingress:certificates jimm-cert:certificates
+    - name: Wait for vault
+      uses: nick-fields/retry@v3
+      with:
+        timeout_minutes: 1
+        max_attempts: 5 # Retry the wait-for with a short timeout in case it gets stuck and times out. If it fails after multiple tries it's probably a real error.
+        command: juju wait-for application vault --timeout=1m --query='name=="vault" && status=="blocked"'
     - name: Set up Vault
       shell: bash
       run: |
@@ -161,15 +167,15 @@ runs:
     - name: Wait for ingress
       uses: nick-fields/retry@v3
       with:
-        timeout_minutes: 10
-        max_attempts: 3
+        timeout_minutes: 1
+        max_attempts: 5 # Retry the wait-for with a short timeout in case it gets stuck and times out. If it fails after multiple tries it's probably a real error.
         command: |
           STATUS=$(juju status --format json | yq .applications.ingress.application-status.current)
           if [ "$STATUS" == "error" ]; then
             # Sometimes the ingress unit will get into an error state, so resolve and try again.
             juju resolved ingress/0
           fi
-          juju wait-for unit ingress/0
+          juju wait-for unit ingress/0 --timeout=1m
     - name: Set up ingress hostname and certs
       shell: bash
       run: |
@@ -180,9 +186,9 @@ runs:
     - name: Wait for JIMM
       uses: nick-fields/retry@v3
       with:
-        timeout_minutes: 10
-        max_attempts: 2 # Retry the wait-for in case it gets stuck and times out. If it fails on the second try it's probably a real error.
-        command: juju wait-for unit jimm/0 # Wait for JIMM to be ready if it's still making config changes.
+        timeout_minutes: 1
+        max_attempts: 5 # Retry the wait-for with a short timeout in case it gets stuck and times out. If it fails after multiple tries it's probably a real error.
+        command: juju wait-for unit jimm/0 --timeout=1m # Wait for JIMM to be ready if it's still making config changes.
     - name: Bootstrap workloads controller
       id: workloads-controller
       shell: bash
@@ -216,20 +222,20 @@ runs:
     - name: Wait for JIMM
       uses: nick-fields/retry@v3
       with:
-        timeout_minutes: 10
-        max_attempts: 2 # Retry the wait-for in case it gets stuck and times out. If it fails on the second try it's probably a real error.
+        timeout_minutes: 1
+        max_attempts: 5 # Retry the wait-for with a short timeout in case it gets stuck and times out. If it fails after multiple tries it's probably a real error.
         command: |
           juju switch '${{ steps.jimm-controller.outputs.name }}:jimm'
           # Wait for JIMM to be ready if it's still making config changes.
-          juju wait-for unit jimm/0
+          juju wait-for unit jimm/0 --timeout=1m
     - name: Restart JIMM
       shell: bash
       run: sudo microk8s kubectl delete pod jimm-0 -n jimm # Fix ListModels issue:
     - name: Wait for JIMM pod to be recreated
       uses: nick-fields/retry@v3
       with:
-        timeout_minutes: 10
-        max_attempts: 2
+        timeout_minutes: 1
+        max_attempts: 5 # Retry the wait-for with a short timeout in case it gets stuck and times out. If it fails after multiple tries it's probably a real error.
         continue_on_error: true # Sometimes the error persists after a retry but it seems to work anyway.
         command: |
           juju switch '${{ steps.jimm-controller.outputs.name }}:jimm'
@@ -238,4 +244,4 @@ runs:
             # Sometimes the jimm unit will get into an error state, so resolve and try again.
             juju resolved jimm/0
           fi
-          juju wait-for application jimm --query='name=="jimm" && (status=="active" || status=="error")'
+          juju wait-for application jimm --timeout=1m --query='name=="jimm" && (status=="active" || status=="error")'
